backend:
  name: git-gateway
  branch: master 

media_folder: "static/images"
public_folder: "static"

collections:
- name: "blog" 
  label: "Blog" 
  folder: "blog"
  create: true 
  slug: "{{slug}}" 
  fields: 
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Excerpt", name: "excerpt", widget: "string"}
    - {label: "Cover Image", name: "coverImage", widget: "image"}
    - {label: "Content", name: "content", widget: "markdown"}
    - {label: "Date", name: "date", widget: "string"}

